### PR TITLE
fix(scripts): register the redactor in sys.modules while loading it

### PR DESCRIPTION
**Pull request by bnaylor**
## Summary

`Python Unit Tests` has been red on every `main` commit since #1364 landed.  `scripts/validate_bench_cases.py` loads the audit redactor by path without registering it in `sys.modules`, which was fine until #1364 gave that file a dataclass.  This registers it, matching the loader the chart already ships.

## Why This Change

`main` is red and stays red until this lands.  Every PR's `Python Unit Tests` inherits the failure, so it is not just cosmetic -- it hides real regressions in anything that touches `scripts/`.

The break is not in #1364.  `credential_patterns()` runs the redactor through `importlib.util.module_from_spec` + `exec_module` without putting it in `sys.modules`, on the theory that loading a file is cheaper than importing a package.  That works right up until the file defines a dataclass.

`agents/chat/defaults/plugins/common/redactor.py` carries `from __future__ import annotations` (line 32), so every field annotation arrives at `dataclasses` as a string.  For an unqualified one like `name: str`, `dataclasses._is_type` probes whether it denotes `KW_ONLY` or `ClassVar` by way of `sys.modules.get(cls.__module__).__dict__` -- unguarded, so a module that was never registered gets `None` and the whole thing dies with `AttributeError: 'NoneType' object has no attribute '__dict__'`.  #1364 added `RedactionRule` with exactly that shape.

Both halves are needed to trigger it.  A qualified annotation like `pattern: "re.Pattern[str]"` takes a different, guarded branch and is harmless, which is why the file's other fields were fine.  The failure surfaces inside `dataclasses`, nowhere near the loader, which is what made it look like a #1364 bug.

## What Changed

- `scripts/validate_bench_cases.py`: register the module under `REDACTOR_MODULE_NAME` before `exec_module`, and leave it there.
- `scripts/test_task_registration.py`: a regression test that builds its own minimal fixture with both halves (`from __future__ import annotations` + an unqualified dataclass field), so it stays a test of the loader after the real redactor's contents move on.

Second commit (60a6ac6e) is the self-review follow-up.  The first version popped the module back out afterwards; that turned out to be worse in three ways, see Self-Review below.

## Context

Bisected to a3fe6f48 (#1364), which merged at 01:48:17Z.  `9fb840e5` at 01:48:07Z was the last green, and #1364's own merge run was already red.  Reproduced against a pristine `origin/main` worktree before touching anything, so this is not an artefact of a local branch.

`charts/kube-agents/files/litellm_redaction_callback.py::_load_redactor` loads this same `redactor.py` at the gateway and hit this first -- it registers before the exec and does not pop.  This change makes the two loaders agree.  Worth knowing if a third one ever shows up: loading a file that defines a dataclass by path means registering it, full stop.

## Testing

- `python3 -m unittest discover -p 'test_*.py'` under `scripts/`: **1416 tests OK** (1 skipped).
- `make bench-case-check`: **33 bench cases OK**.
- Regression test verified in both directions.  Against `origin/main`'s loader it fails with the exact production error (`could not be imported: 'NoneType' object has no attribute '__dict__'`); with the fix it passes.
- Ran the loader against Python **3.12.8, 3.13.7 and 3.14.2** -- unregistered raises, registered loads, behaviour identical on all three.  CI pins `.python-version` to 3.12 and the agent-plugin workflows use `.agent-python-version` 3.13, so both are covered.
- `git status` clean, `make docs-check` exit 0.

## Live validation

**Not live-tested.**  This is a test-infrastructure fix in `scripts/` -- `validate_bench_cases.py` runs in CI and from `make bench-case-check`, and never reaches a running installation.  There is nothing on the dev cluster to point it at.  The equivalent of a live run here is executing the real validator against the real redactor, which is what `make bench-case-check` does, and it is in Testing above.

## Self-Review

Two passes, both run in **fresh general-purpose subagent contexts** that did not write the change -- each was handed the diff range and nothing else.

**Docs-drift pass.  Zero findings.**  Looked for docs asserting the old "loaded, not imported" property or describing the validator's contract.  Searched `validate_bench_cases`, `credential_patterns`, `bench-case-check`, `REDACTOR_MODULE_NAME`, `REDACTOR_FILE`, `REDACTOR_CLASS`, `CREDENTIAL_SHAPES`, `sanitization_findings`, `AuditRedactor`, `test_task_registration`, `RedactionRule`, `sys.modules`, `spec_from_file_location`.  Read `AGENTS.md:53-54`, `docs/designs/bench-case-format.md:291-341,357`, `bench/CONTRIBUTING.md:58-70`, `bench/CUSTOM-TASKS.md:238-250`, `docs/testing-map.md:96-102`, `docs/README.md:334,439`, `tests/conformance/README.md:161-162`.  All unaffected -- the docstring's "loaded from the file rather than imported as a package" claim is about `sys.path` and package semantics, not `sys.modules`, and is still true.

**Adversarial pass.  Nine checks, four findings, three fixed and one accepted.**

- **MEDIUM, fixed in 60a6ac6e** -- the unconditional `sys.modules.pop` destroyed a pre-existing entry instead of restoring it.  Confirmed by execution, not just by reading.
- **MEDIUM, fixed in 60a6ac6e** -- diverged from `_load_redactor` in the chart, which already solves this identically and leaves the module registered.  I verified this one against the file myself rather than taking the pass's word for it.  Two loaders of the same redactor with two conventions, and mine was the riskier.  Now they match, which retires the first finding too.
- **LOW, fixed in 60a6ac6e** -- the test's closing assertion was vacuous.  `assertNotIn(REDACTOR_MODULE_NAME, sys.modules)` passes identically on unfixed `main`, where nothing is ever registered.  It now asserts the module is present and is the one that was loaded, and it fails on `main` with the original `AttributeError`.
- **NIT, fixed in 60a6ac6e** -- "resolved through `sys.modules`" in both comments.  `dataclasses` is not resolving the annotation, it is probing whether it denotes `KW_ONLY`/`ClassVar`.  The wrong word points a reader at a different and wrong fix.
- Clean: the test genuinely reproduces the bug (verified by execution both ways); no state leakage between tests; the stdlib claim in the comments is accurate against `dataclasses._is_type` source; no 3.12-vs-3.14 divergence; `CaseError` wrapping is correct.

Nothing was left deliberately unfixed.

Worth flagging for the reviewer since it is a judgement call rather than a defect: I chose "register and leave it" over "save and restore" because it matches the chart loader.  Save/restore would keep `sys.modules` marginally tidier, at the cost of two loaders of one file disagreeing, and of handing back a module whose own dataclass annotations no longer resolve.

## Risk & Rollout

Low.  The change is three lines in a CI-only script plus a test.  `REDACTOR_MODULE_NAME` (`kube_agents_audit_redactor`) is ours alone and matches no package, so registering it displaces nothing -- the comment at its definition claimed as much already, and this makes the claim load-bearing.

Rollback is a revert; it puts `main`'s Python job back to red but breaks nothing else.  No runtime, chart, or operator surface is touched.

### CODE REVIEW

**Comment by bnaylor** [comment]
Both findings were the same defect: the body was freeform and did not fill `.github/PULL_REQUEST_TEMPLATE.md`.  Rewritten to the template, with Live validation answered ("Not live-tested", and why) and Self-Review naming the kind of context each pass ran in.

The Self-Review pass was not free -- it found four things, three of which changed the code.  60a6ac6e replaces the original "register, then pop it back out" with "register and leave it", which is what `_load_redactor` in `charts/kube-agents/files/litellm_redaction_callback.py` already does with this same `redactor.py`.  It also fixes a regression assertion that was vacuous: `assertNotIn(REDACTOR_MODULE_NAME, sys.modules)` passes on unfixed `main` too, since that never registers anything.  Dispositions are all in the body.

`/review`

File: scripts/test_task_registration.py [hunk 1]
```diff
@@ -42,6 +42,7 @@
 import re
```
[the remark this answers is not in the document]
Comment (bnaylor) [reply scripts/test_task_registration.py:42]: Fixed. The body now fills every section of `.github/PULL_REQUEST_TEMPLATE.md`, including the two this finding named specifically.

**Live validation** answers "Not live-tested" and says why: this is a test-infrastructure fix in `scripts/` that CI and `make bench-case-check` run, and it never reaches a running installation, so there is nothing on the dev cluster to point it at. The nearest equivalent is running the real validator against the real redactor, which `make bench-case-check` does (33 cases OK).

**Self-Review** names the kind of context each pass ran in -- both were fresh general-purpose subagents handed the diff range and nothing else, neither having written the change -- and records each finding's disposition. It was not a formality: the adversarial pass produced four findings and three of them changed the code in 60a6ac6e. The substantive one was that this loader had diverged from `_load_redactor` in `charts/kube-agents/files/litellm_redaction_callback.py`, which loads this same `redactor.py` at the gateway and already solved this bug by registering and leaving it registered. It also caught that my regression assertion was vacuous -- `assertNotIn(REDACTOR_MODULE_NAME, sys.modules)` passes on unfixed main too, since main never registers anything.

Re-read is clean (`AI Review`: No findings) and `Run Python Unit Tests` is green on the runner. Resolving.

**Comment by bnaylor** [comment]
**Status note, because this PR's title undersells what it is blocking: `main` is red and the merge queue has been stopped for 7.5 hours.**

`Run Python Unit Tests` is one of the ten contexts `main` requires (`docs/pull-request-workflow.md:323`), and it fails on pristine `main` right now:

```
$ git checkout 76463db1 && cd scripts && python3 -m unittest test_task_registration
Ran 89 tests in 0.941s
FAILED (failures=2, errors=36)
```

Because `pull_request` workflows build `refs/pull/N/merge` -- head merged with the *current* base -- every open PR inherits it regardless of whether its branch has merged `main`. Spot-checked six PRs from other authors: #1462, #1457, #1456 and #1455 are all red on that check. The two green ones carry results predating the breakage.

**Timeline.** #1364 merged at 01:48:14Z and added `@dataclass(frozen=True) class RedactionRule` to `agents/chat/defaults/plugins/common/redactor.py`, which already carried `from __future__ import annotations` at line 32. That is both halves of the trap this PR fixes: the annotation reaches `dataclasses` as a string, and an unqualified one like `name: str` gets probed for `KW_ONLY` via `sys.modules[cls.__module__].__dict__`, which is unguarded and dies on `None` for a module that was never registered. The last merge to `main` was #1437 at 01:49:19Z. Nothing has merged since.

Nothing is wrong with #1364 -- `scripts/validate_bench_cases.py` was loading that module in a way that only worked as long as it defined no dataclass, and this PR makes the loader match the one already shipping in `charts/kube-agents/files/litellm_redaction_callback.py`.

No issue is open for this and I have not filed one, since this PR is the fix and a separate issue would only split the thread. Flagging the blast radius rather than asking for anything: this is green, has no unresolved threads, and needs one approval.

I am triage-only on this repository, so `/override` is not available to me if an admin would rather force the check while this is reviewed.

**Review by mplakhtiy — APPROVED** [review]

**Review by eLeontev — APPROVED** [review]
