### PR TITLE
ci: add GitHub Actions workflow to run operator integration tests

### PR DESCRIPTION
**Pull request by shalinibhatiapl**
# Pull Request

## Why This Change

Currently, the `k8s-operator` has unit and golden integration tests, but they must be run manually by developers. There is no automated CI/CD pipeline step to enforce that tests pass before merging a Pull Request. 

This change adds a GitHub Actions workflow to run the tests automatically on every PR modifying the operator codebase.

## What Changed

**Files:**

- [.github/workflows/k8s-operator-test.yml](file:///.github/workflows/k8s-operator-test.yml)

**Added/Changed/Fixed:**

- **Added Operator Test Workflow**: Created a new GitHub Actions workflow to run the operator tests (`make -C k8s-operator test`) on pull requests and pushes to `main` that modify the `k8s-operator/` directory.
- **Enabled Setup-Go caching**: Configured the Go setup action to cache module dependencies for faster CI runs.

## Why This Matters

- Catches compilation errors and integration test failures automatically during the PR review process.
- Ensures all future controller updates and golden test updates are validated before being merged to `main`.

## Context

- Enforces the golden test suite introduced in PR #206 and expanded in the PlatformAgent testing work.

## Testing

- Validated the workflow syntax locally using `actionlint`:
```bash
curl -sSfL "https://github.com/rhysd/actionlint/releases/download/v1.7.7/actionlint_1.7.7_linux_amd64.tar.gz" -o actionlint.tar.gz && tar -xzf actionlint.tar.gz actionlint && ./actionlint .github/workflows/k8s-operator-test.yml
```
- Test Run
https://github.com/gke-agentic/kube-agents/actions/runs/28104569158

Result: `actionlint` completed successfully with **zero errors**.

### CODE REVIEW

**Comment by shalinibhatiapl** [comment]
Hey @bradhoekstra, We've added a GitHub Actions workflow (.github/workflows/k8s-operator-test.yml) to automatically run the operator integration tests on every PR commit/push. Could you please review this PR and configure the "Operator Tests" status check as a required passing check for the main branch so that future PRs are blocked from merging if tests fail?

Thank you.

**Review by eLeontev — APPROVED** [review]

**Review by fatoshoti — APPROVED** [review]

**Review by haoxuw — APPROVED** [review]
LGTM!
